version: "2.4"

services:
  app:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: Dockerfile.dev
    volumes:
      # Host source code directory
      - ../:/app/
      # The line below is useful if using dbt interactively; should not be
      # needed for automated tests.
    entrypoint: /bin/bash
    tty: true