name: "jaffle_shop_duckdb"

config-version: 2
version: "0.1"

profile: "jaffle_shop"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop_duckdb:
    +jinjat:
      cors: true

on-run-end:
  - "{{jinjat_metadata_api.upload_results(results) }}"

vars:
  start_date: '2016-06-01'