jaffle_shop:
  target: test
  outputs:
    dev:
      type: duckdb
      path: "demo_duckdb/jaffle_shop.duckdb"
      settings:
        access_mode: READ_ONLY
    test:
      type: duckdb
      path: "/Users/bkabak/Code/jinjat/jinjat/demo_duckdb/jaffle_shop.duckdb"
#      settings:
#        access_mode: READ_ONLY
  